EMOJIS = [
    "\N{AUBERGINE}",
    "\N{SMIRKING FACE}",
    "\N{PEACH}",
    "\N{SPLASHING SWEAT SYMBOL}",
    "\N{BANANA}",
    "\N{KISS MARK}",
]
NEKOBOT_BASEURL = "https://nekobot.xyz/api/image?type="

FOUR_K = ["HighResNSFW", "UHDnsfw", "nsfw4k", "nsfw_hd", "NSFW_Wallpapers", "HDnsfw", "closeup"]
AHEGAO = ["AhegaoGirls", "RealAhegao", "EyeRollOrgasm", "MouthWideOpen"]
ASS = [
    "ass",
    "pawg",
    "AssholeBehindThong",
    "girlsinyogapants",
    "girlsinleggings",
    "bigasses",
    "asshole",
    "AssOnTheGlass",
    "TheUnderbun",
    "asstastic",
    "booty",
    "AssReveal",
    "beautifulbutt",
    "Mooning",
    "BestBooties",
    "brunetteass",
    "assinthong",
    "paag",
    "asstastic",
    "GodBooty",
    "Underbun",
    "datass",
    "ILikeLittleButts",
]
ANAL = [
    "MasterOfAnal",
    "analgonewild",
    "anal",
    "buttsex",
    "buttsthatgrip",
    "AnalGW",
    "analinsertions",
    "AnalGW",
    "assholegonewild",
]
BDSM = ["BDSMGW", "bdsm", "ropeart", "shibari"]
BLACKCOCK = ["ChurchOfTheBBC", "blackcock", "Blackdick", "bigblackcocks"]
BLOWJOB = [
    "blowjobsandwich",
    "Blowjobs",
    "BlowjobGifs",
    "BlowjobEyeContact",
    "blowbang",
    "AsianBlowjobs",
    "SuckingItDry",
    "OralCreampie",
    "SwordSwallowers",
]
BOOBS = [
    "boobs",
    "TheHangingBoobs",
    "bigboobs",
    "BigBoobsGW",
    "hugeboobs",
    "pokies",
    "ghostnipples",
    "PiercedNSFW",
    "piercedtits",
    "PerfectTits",
    "BestTits",
    "Boobies",
    "JustOneBoob",
    "tits",
    "naturaltitties",
    "smallboobs",
    "Nipples",
    "homegrowntits",
    "TheUnderboob",
    "BiggerThanYouThought",
    "fortyfivefiftyfive",
    "Stacked",
    "BigBoobsGonewild",
    "AreolasGW",
    "TittyDrop",
    "Titties",
    "Boobies",
    "boobbounce",
    "TinyTits",
    "cleavage",
    "BoobsBetweenArms",
    "BustyNaturals",
]
BOTTOMLESS = ["upskirt", "Bottomless", "Bottomless_Vixens", "nopanties", "Pantiesdown"]
CUNNI = ["cunnilingus", "eatpussy2015", "CunnilingusSelfie", "Hegoesdown"]
CUMSHOTS = [
    "cumfetish",
    "cumontongue",
    "cumshots",
    "CumshotSelfies",
    "facialcumshots",
    "pulsatingcumshots",
    "gwcumsluts",
    "ImpresssedByCum",
    "GirlsFinishingTheJob",
    "cumshot",
    "amateurcumsluts",
    "unexpectedcum",
    "bodyshots",
    "ContainTheLoad",
    "bodyshots",
]
DEEPTHROAT = ["DeepThroatTears", "deepthroat", "SwordSwallowers"]
DICK = ["DickPics4Freedom", "mangonewild", "MassiveCock", "penis", "cock", "ThickDick"]
DOUBLE_P = ["doublepenetration", "dp_porn", "Technical_DP"]
GAY_P = ["gayporn", "GayPornForStrtGuys", "ladybonersgw", "mangonewild"]
GROUPS = ["GroupOfNudeGirls", "GroupOfNudeMILFs", "groupsex"]
# HENTAI = ["hentai", "thick_hentai", "HQHentai", "AnimeBooty", "thighdeology"]
# HENTAI_GIFS = ["ecchigifs", "nsfwanimegifs", "oppai_gif"]
LESBIANS = ["lesbians", "HDLesbianGifs", "amateurlesbians", "Lesbian_gifs"]
MILF = [
    "amateur_milfs",
    "GroupOfNudeMILFs",
    "ChocolateMilf",
    "milf",
    "Milfie",
    "hairymilfs",
    "HotAsianMilfs",
    "HotMILFs",
    "MILFs",
    "maturemilf",
    "puremilf",
    "amateur_milfs",
]
ORAL = [
    "blowjobsandwich",
    "Blowjobs",
    "BlowjobGifs",
    "BlowjobEyeContact",
    "blowbang",
    "AsianBlowjobs",
    "SuckingItDry",
    "OralCreampie",
    "cunnilingus",
    "eatpussy2015",
    "CunnilingusSelfie",
    "Hegoesdown",
    "DeepThroatTears",
    "deepthroat",
    "ballsucking",
    "SwordSwallowers",
]
PUBLIC = [
    "RealPublicNudity",
    "FlashingAndFlaunting",
    "FlashingGirls",
    "PublicFlashing",
    "Unashamed",
    "OutsideNude",
    "NudeInPublic",
    "publicplug",
    "casualnudity",
]
PUSSY = [
    "pussy",
    "GodPussy",
    "AsianPussy",
    "rearpussy",
    "PussyFlashing",
    "Innies",
    "pelfie",
    "GirlsWithToys",
    "simps",
    "LabiaGW",
    "grool",
]
REAL_GIRLS = ["RealGirls", "RealGirlsGoneWild", "Nude_Selfie"]
RULE_34 = [
    "rule34",
    "rule34cartoons",
    "Rule_34",
    "Rule34LoL",
    "AvatarPorn",
    "Overwatch_Porn",
    "Rule34Overwatch",
    "WesternHentai",
]
THIGHS = ["Thighs", "ThickThighs", "thighhighs", "Thigh", "leggingsgonewild"]
TRAPS = [
    "Transex",
    "DeliciousTraps",
    "traps",
    "trapgifs",
    "GoneWildTrans",
    "SexyShemales",
    "Shemales",
    "shemale_gifs",
    "Shemales",
    "ShemalesParadise",
    "Shemale_Big_Cock",
    "ShemaleGalleries",
]
WILD = [
    "gonewild",
    "GWNerdy",
    "dirtysmall",
    "MyCalvins",
    "AsiansGoneWild",
    "GoneWildSmiles",
    "gonewildcurvy",
    "BigBoobsGonewild",
    "gonewildcouples",
    "gonewildcolor",
    "PetiteGoneWild",
    "GWCouples",
    "BigBoobsGW",
    "altgonewild",
    "LabiaGW",
    "UnderwearGW",
    "JustTheTop",
    "TallGoneWild",
    "LingerieGW",
    "Swingersgw",
]
